# ============================================================
# Rerun E1 A1: activity-aligned training and activity-aligned evaluation
# Fold B, stream bone
# Generated by rerun/e1/generate_stgcnpp_configs.py
# ============================================================

stream = 'b'
dataset_type = 'PoseDataset'
ann_file = 'data/radar_v4/rerun/yolo26xpose/pyskl/activity_aligned/radarv4_yolo26xpose_activity_aligned_fold_b.pkl'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        num_person=1,
        gcn_adaptive='init',
        gcn_with_res=True,
        tcn_type='mstcn',
        graph_cfg=dict(layout='coco', mode='spatial')
    ),
    cls_head=dict(
        type='GCNHead',
        num_classes=9,
        in_channels=256,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    )
)

# Subject-wise outer split:
# Train subjects: han, jiadi, li, mia, rose, saad, xilai, yunze
# Validation subject: hui
# Calibration subject: chenzhe
# Test subject: dengdeng
# Square-root training sampler:
# Each sample i has weight a_i = 1 / sqrt(n_yi).
# Sampling is with replacement; one epoch requests N_train samples.
# DDP may add <= world_size - 1 padded samples internally for equal rank lengths.
# N_train = 5969
# Natural train counts and expected requested draws per epoch:
# 0: lie-stationary: n=887, expected=779.6
# 1: sit-stationary: n=468, expected=566.3
# 2: walk: n=1030, expected=840.1
# 3: fall: n=454, expected=557.7
# 4: transition-lie-to-sit: n=447, expected=553.4
# 5: transition-lie-to-stand: n=442, expected=550.3
# 6: transition-sit-to-lie: n=448, expected=554.0
# 7: transition-sit-to-stand: n=894, expected=782.7
# 8: transition-stand-to-sit: n=899, expected=784.8
class_sample_strategy = 'sqrt'
class_sample_power = 0.5
epoch_size = 5969

# COCO-17 left/right keypoint ids
coco_left = [1, 3, 5, 7, 9, 11, 13, 15]
coco_right = [2, 4, 6, 8, 10, 12, 14, 16]

train_pipeline = [
    dict(
        type='Flip',
        flip_ratio=0.5,
        direction='horizontal',
        left_kp=coco_left,
        right_kp=coco_right
    ),
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

val_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

test_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

optimizer = dict(
    type='SGD',
    lr=0.05,
    momentum=0.9,
    weight_decay=0.0005,
    nesterov=True
)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False)
total_epochs = 20
checkpoint_config = dict(interval=1)
evaluation = dict(
    interval=1,
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,))),
    save_best='macro_f1',
    rule='greater'
)
test_evaluation = dict(
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,)))
)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
log_level = 'INFO'
load_from = None
resume_from = None
auto_resume = False
find_unused_parameters = False
work_dir = './work_dirs/rerun/e1/fold_b/bone/a1_activity_aligned'

sampler_indices_output_dir = f'{work_dir}/sampler_indices'

data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    persistent_workers=False,
    train_dataloader=dict(
        sampler_indices_output_dir=sampler_indices_output_dir,
        sampler_indices_output_prefix='sqrt_sampler'
    ),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split='train',
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='val'),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='test')
)
