# ============================================================
# Rerun E1 A2: activity-aligned checkpoint, continuous-window evaluation
# Fold B, stream bone
# Generated by rerun/e1/generate_stgcnpp_configs.py
# ============================================================

stream = 'b'
dataset_type = 'PoseDataset'
ann_file = 'data/radar_v4/rerun/yolo26xpose/pyskl/continuous_window_w60_s12/radarv4_yolo26xpose_continuous_window_w60_s12_fold_b.pkl'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        num_person=1,
        gcn_adaptive='init',
        gcn_with_res=True,
        tcn_type='mstcn',
        graph_cfg=dict(layout='coco', mode='spatial')
    ),
    cls_head=dict(
        type='GCNHead',
        num_classes=9,
        in_channels=256,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    )
)

# Subject-wise outer split:
# Train subjects: han, jiadi, li, mia, rose, saad, xilai, yunze
# Validation subject: hui
# Calibration subject: chenzhe
# Test subject: dengdeng
# COCO-17 left/right keypoint ids
coco_left = [1, 3, 5, 7, 9, 11, 13, 15]
coco_right = [2, 4, 6, 8, 10, 12, 14, 16]

train_pipeline = [
    dict(
        type='Flip',
        flip_ratio=0.5,
        direction='horizontal',
        left_kp=coco_left,
        right_kp=coco_right
    ),
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

val_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

test_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    persistent_workers=False,
    test_dataloader=dict(videos_per_gpu=1),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='test')
)

test_evaluation = dict(
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1, 5)))
)
log_level = 'INFO'
find_unused_parameters = False
work_dir = './work_dirs/rerun/e1/fold_b/bone/a2_continuous_window'
