# ============================================================
# Study 6 continuous hard center-time adaptation of skeleton teacher
# Fold a, teacher t1, stream limb
# Generated by thesis/s6/generate_continuous_configs.py
# ============================================================

stream = 'limb'
ann_file = 'data/radar_v4/pyskl/s2/radarv4_yolo26xpose_clip60_s2_teacher4_s6_continuous.pkl'
dataset_type = 'PoseDataset'

model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowOnly',
        in_channels=17,
        base_channels=32,
        num_stages=3,
        out_indices=(2, ),
        stage_blocks=(4, 6, 3),
        conv1_stride=(1, 1),
        pool1_stride=(1, 1),
        inflate=(0, 1, 1),
        spatial_strides=(2, 2, 2),
        temporal_strides=(1, 1, 2)
    ),
    cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=9,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    ),
    test_cfg=dict(average_clips='prob')
)

# COCO-17 left/right keypoint ids
left_kp = [1, 3, 5, 7, 9, 11, 13, 15]
right_kp = [2, 4, 6, 8, 10, 12, 14, 16]
skeletons = [[0, 5], [0, 6], [5, 7], [7, 9], [6, 8], [8, 10], [5, 11],
             [11, 13], [13, 15], [6, 12], [12, 14], [14, 16], [0, 1], [0, 2],
             [1, 3], [2, 4], [11, 12]]
left_limb = [0, 2, 3, 6, 7, 8, 12, 14]
right_limb = [1, 4, 5, 9, 10, 11, 13, 15]

# S6 teacher-4 continuous split:
# Source fold: fold_a
# Teacher: t1
# Train subjects: li, mia, rose, saad, xilai, yunze
# Validation subject: han
# Calibration subject: dengdeng
# Pseudo-label target/test split: hui, jiadi
# Original fold test subject unused here: chenzhe
# Continuous pkl is derived from the zero-frame-filtered S2 windows.
train_split = 'fold_a_t1_train'
val_split = 'fold_a_t1_val'
test_split = 'fold_a_t1_pseudo'
# Stage-2 teacher fine-tuning samples are drawn each epoch from pre-gridded train windows.
# class_sample_strategy: sqrt; class_sample_power: 0.5; epoch_size: 34147
# Class draw rule: P(c) = n_c ** class_sample_power / sum_j n_j ** class_sample_power.
# After drawing a class, one pre-gridded window from that class is sampled uniformly with replacement.
# Train window counts and expected draws per epoch:
# Falling: n=1105, p=0.067878, expected_epoch_samples=2317.8
# Lying-Stationary: n=5684, p=0.153949, expected_epoch_samples=5256.9
# Sit-Stationary: n=3500, p=0.120805, expected_epoch_samples=4125.1
# Transition-LayBed-to-Sit: n=1313, p=0.073992, expected_epoch_samples=2526.6
# Transition-LayFloor-to-Stand: n=2634, p=0.104799, expected_epoch_samples=3578.6
# Transition-Sit-to-LayBed: n=1252, p=0.072252, expected_epoch_samples=2467.2
# Transition-Sit-to-Stand: n=1125, p=0.068490, expected_epoch_samples=2338.7
# Transition-Stand-to-Sit: n=1510, p=0.079349, expected_epoch_samples=2709.5
# Walking: n=16024, p=0.258485, expected_epoch_samples=8826.5
class_sample_strategy = 'sqrt'
class_sample_power = 0.5
epoch_size = 34147

generate_pose_target = dict(
    joint=dict(with_kp=True, with_limb=False),
    limb=dict(with_kp=False, with_limb=True, skeletons=skeletons)
)[stream]

generate_pose_target_test = dict(
    joint=dict(
        with_kp=True,
        with_limb=False,
        double=True,
        left_kp=left_kp,
        right_kp=right_kp
    ),
    limb=dict(
        with_kp=False,
        with_limb=True,
        skeletons=skeletons,
        double=True,
        left_kp=left_kp,
        right_kp=right_kp,
        left_limb=left_limb,
        right_limb=right_limb
    )
)[stream]

train_pipeline = [
    dict(type='UniformSampleFrames', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='RandomResizedCrop', area_range=(0.56, 1.0)),
    dict(type='Resize', scale=(56, 56), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5, left_kp=left_kp, right_kp=right_kp),
    dict(type='GeneratePoseTarget', **generate_pose_target),
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]

val_pipeline = [
    dict(type='UniformSampleFrames', clip_len=60, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(64, 64), keep_ratio=False),
    dict(type='GeneratePoseTarget', **generate_pose_target),
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

test_pipeline = [
    dict(type='UniformSampleFrames', clip_len=60, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(64, 64), keep_ratio=False),
    dict(type='GeneratePoseTarget', **generate_pose_target_test),
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

find_unused_parameters = False
data = dict(
    videos_per_gpu=8,
    workers_per_gpu=1,
    persistent_workers=False,
    train_dataloader=dict(pin_memory=False),
    val_dataloader=dict(pin_memory=False),
    test_dataloader=dict(videos_per_gpu=1, pin_memory=False),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split=train_split,
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, split=val_split, pipeline=val_pipeline),
    test=dict(type=dataset_type, ann_file=ann_file, split=test_split, pipeline=test_pipeline)
)

optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0003)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
lr_config = dict(policy='CosineAnnealing', by_epoch=False, min_lr=0)
total_epochs = 8
checkpoint_config = dict(interval=1)
evaluation = dict(
    interval=1,
    metrics=['top_k_accuracy', 'mean_class_accuracy', 'macro_f1', 'state_macro_f1', 'transition_macro_f1'],
    topk=(1, 5),
    save_best='macro_f1',
    rule='greater'
)
test_evaluation = dict(
    metrics=['top_k_accuracy', 'mean_class_accuracy', 'macro_f1', 'state_macro_f1',
             'transition_macro_f1', 'per_class_f1', 'confusion_matrix'],
    topk=(1, 5)
)
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
log_level = 'INFO'
load_from = 'work_dirs/thesis/s6/trimmed/fold_a/t1/limb/best_macro_f1_epoch_9.pth'
resume_from = None
auto_resume = False
work_dir = './work_dirs/thesis/s6/continuous_hard/fold_a/t1/limb'
