# ============================================================
# Study 6 continuous hard center-time adaptation of skeleton teacher
# Fold c, teacher t2, stream joint
# Generated by thesis/s6/generate_continuous_configs.py
# ============================================================

stream = 'joint'
ann_file = 'data/radar_v4/pyskl/s2/radarv4_yolo26xpose_clip60_s2_teacher4_s6_continuous.pkl'
dataset_type = 'PoseDataset'

model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowOnly',
        in_channels=17,
        base_channels=32,
        num_stages=3,
        out_indices=(2, ),
        stage_blocks=(4, 6, 3),
        conv1_stride=(1, 1),
        pool1_stride=(1, 1),
        inflate=(0, 1, 1),
        spatial_strides=(2, 2, 2),
        temporal_strides=(1, 1, 2)
    ),
    cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=9,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    ),
    test_cfg=dict(average_clips='prob')
)

# COCO-17 left/right keypoint ids
left_kp = [1, 3, 5, 7, 9, 11, 13, 15]
right_kp = [2, 4, 6, 8, 10, 12, 14, 16]
skeletons = [[0, 5], [0, 6], [5, 7], [7, 9], [6, 8], [8, 10], [5, 11],
             [11, 13], [13, 15], [6, 12], [12, 14], [14, 16], [0, 1], [0, 2],
             [1, 3], [2, 4], [11, 12]]
left_limb = [0, 2, 3, 6, 7, 8, 12, 14]
right_limb = [1, 4, 5, 9, 10, 11, 13, 15]

# S6 teacher-4 continuous split:
# Source fold: fold_c
# Teacher: t2
# Train subjects: chenzhe, dengdeng, jiadi, li, mia, rose
# Validation subject: yunze
# Calibration subject: xilai
# Pseudo-label target/test split: han, hui
# Original fold test subject unused here: saad
# Continuous pkl is derived from the zero-frame-filtered S2 windows.
train_split = 'fold_c_t2_train'
val_split = 'fold_c_t2_val'
test_split = 'fold_c_t2_pseudo'
# Stage-2 teacher fine-tuning samples are drawn each epoch from pre-gridded train windows.
# class_sample_strategy: sqrt; class_sample_power: 0.5; epoch_size: 34346
# Class draw rule: P(c) = n_c ** class_sample_power / sum_j n_j ** class_sample_power.
# After drawing a class, one pre-gridded window from that class is sampled uniformly with replacement.
# Train window counts and expected draws per epoch:
# Falling: n=1066, p=0.066342, expected_epoch_samples=2278.6
# Lying-Stationary: n=7262, p=0.173155, expected_epoch_samples=5947.2
# Sit-Stationary: n=3267, p=0.116140, expected_epoch_samples=3988.9
# Transition-LayBed-to-Sit: n=1412, p=0.076353, expected_epoch_samples=2622.4
# Transition-LayFloor-to-Stand: n=3108, p=0.113278, expected_epoch_samples=3890.7
# Transition-Sit-to-LayBed: n=1142, p=0.068666, expected_epoch_samples=2358.4
# Transition-Sit-to-Stand: n=1095, p=0.067238, expected_epoch_samples=2309.4
# Transition-Stand-to-Sit: n=1263, p=0.072212, expected_epoch_samples=2480.2
# Walking: n=14731, p=0.246617, expected_epoch_samples=8470.3
class_sample_strategy = 'sqrt'
class_sample_power = 0.5
epoch_size = 34346

generate_pose_target = dict(
    joint=dict(with_kp=True, with_limb=False),
    limb=dict(with_kp=False, with_limb=True, skeletons=skeletons)
)[stream]

generate_pose_target_test = dict(
    joint=dict(
        with_kp=True,
        with_limb=False,
        double=True,
        left_kp=left_kp,
        right_kp=right_kp
    ),
    limb=dict(
        with_kp=False,
        with_limb=True,
        skeletons=skeletons,
        double=True,
        left_kp=left_kp,
        right_kp=right_kp,
        left_limb=left_limb,
        right_limb=right_limb
    )
)[stream]

train_pipeline = [
    dict(type='UniformSampleFrames', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='RandomResizedCrop', area_range=(0.56, 1.0)),
    dict(type='Resize', scale=(56, 56), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5, left_kp=left_kp, right_kp=right_kp),
    dict(type='GeneratePoseTarget', **generate_pose_target),
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]

val_pipeline = [
    dict(type='UniformSampleFrames', clip_len=60, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(64, 64), keep_ratio=False),
    dict(type='GeneratePoseTarget', **generate_pose_target),
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

test_pipeline = [
    dict(type='UniformSampleFrames', clip_len=60, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(64, 64), keep_ratio=False),
    dict(type='GeneratePoseTarget', **generate_pose_target_test),
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

find_unused_parameters = False
data = dict(
    videos_per_gpu=8,
    workers_per_gpu=1,
    persistent_workers=False,
    train_dataloader=dict(pin_memory=False),
    val_dataloader=dict(pin_memory=False),
    test_dataloader=dict(videos_per_gpu=1, pin_memory=False),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split=train_split,
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, split=val_split, pipeline=val_pipeline),
    test=dict(type=dataset_type, ann_file=ann_file, split=test_split, pipeline=test_pipeline)
)

optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0003)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
lr_config = dict(policy='CosineAnnealing', by_epoch=False, min_lr=0)
total_epochs = 8
checkpoint_config = dict(interval=1)
evaluation = dict(
    interval=1,
    metrics=['top_k_accuracy', 'mean_class_accuracy', 'macro_f1', 'state_macro_f1', 'transition_macro_f1'],
    topk=(1, 5),
    save_best='macro_f1',
    rule='greater'
)
test_evaluation = dict(
    metrics=['top_k_accuracy', 'mean_class_accuracy', 'macro_f1', 'state_macro_f1',
             'transition_macro_f1', 'per_class_f1', 'confusion_matrix'],
    topk=(1, 5)
)
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
log_level = 'INFO'
load_from = 'work_dirs/thesis/s6/trimmed/fold_c/t2/joint/best_macro_f1_epoch_12.pth'
resume_from = None
auto_resume = False
work_dir = './work_dirs/thesis/s6/continuous_hard/fold_c/t2/joint'
