# ============================================================
# Rerun pseudo-labeling inner teacher: direct continuous-window ST-GCN++
# Outer fold A, teacher T3, stream bone
# Generated by rerun/pseudo_labeling/generate_inner_teacher_training_artifacts.py
# ============================================================

stream = 'b'
dataset_type = 'PoseDataset'
ann_file = 'data/radar_v4/rerun/yolo26xpose/pyskl/inner_teachers_continuous_window_w60_s12/radarv4_yolo26xpose_continuous_window_w60_s12_inner_fold_a_t3_bone.pkl'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        num_person=1,
        gcn_adaptive='init',
        gcn_with_res=True,
        tcn_type='mstcn',
        graph_cfg=dict(layout='coco', mode='spatial')
    ),
    cls_head=dict(
        type='GCNHead',
        num_classes=9,
        in_channels=256,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    )
)

# Fixed outer roles:
# Outer validation subject: han
# Outer calibration subject: saad
# Outer test subject excluded: li
# Inner cross-fitting roles:
# Train subjects: chenzhe, hui, mia, rose, xilai, yunze
# Pseudo-target subjects: dengdeng, jiadi
# Pseudo-target windows: 10103
# `data.test` intentionally uses split='pseudo_target' for --test-best.
# The outer test subject is not present in this pkl.
# Square-root training sampler:
# Each sample i has weight a_i = 1 / sqrt(n_yi).
# Sampling is with replacement; one epoch requests N_train samples.
# DDP may add <= world_size - 1 padded samples internally for equal rank lengths.
# N_train = 33190
# Natural train counts and expected requested draws per epoch:
# 0: lie-stationary: n=5752, expected=5189.9
# 1: sit-stationary: n=3002, expected=3749.3
# 2: walk: n=15271, expected=8456.3
# 3: fall: n=1122, expected=2292.2
# 4: transition-lie-to-sit: n=1420, expected=2578.6
# 5: transition-lie-to-stand: n=2837, expected=3644.8
# 6: transition-sit-to-lie: n=1242, expected=2411.6
# 7: transition-sit-to-stand: n=1081, expected=2249.9
# 8: transition-stand-to-sit: n=1463, expected=2617.4
class_sample_strategy = 'sqrt'
class_sample_power = 0.5
epoch_size = 33190

# COCO-17 left/right keypoint ids
coco_left = [1, 3, 5, 7, 9, 11, 13, 15]
coco_right = [2, 4, 6, 8, 10, 12, 14, 16]

train_pipeline = [
    dict(
        type='Flip',
        flip_ratio=0.5,
        direction='horizontal',
        left_kp=coco_left,
        right_kp=coco_right
    ),
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

val_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

test_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

optimizer = dict(
    type='SGD',
    lr=0.05,
    momentum=0.9,
    weight_decay=0.0005,
    nesterov=True
)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False)
total_epochs = 20
checkpoint_config = dict(interval=1)
evaluation = dict(
    interval=1,
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,))),
    save_best='macro_f1',
    rule='greater'
)
test_evaluation = dict(
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,)))
)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
log_level = 'INFO'
load_from = None
resume_from = None
auto_resume = False
find_unused_parameters = False
work_dir = './work_dirs/rerun/pseudo_labeling/inner_teachers/fold_a/t3/bone'

sampler_indices_output_dir = f'{work_dir}/sampler_indices'

data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    persistent_workers=False,
    train_dataloader=dict(
        sampler_indices_output_dir=sampler_indices_output_dir,
        sampler_indices_output_prefix='sqrt_sampler'
    ),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split='train',
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='val'),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='pseudo_target')
)
