"""Generate four project ST-GCN++ configs and one SLURM job per stream.

Run from the repository root after building the phase-0 project dataset.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from project.dataset.build_radar_v4_10fps import SPLIT_SUBJECTS
from rerun.e1.generate_stgcnpp_configs import (
    LABELS, model_block, pipeline_block, runtime_block, sqrt_expected_draws,
)


STREAMS = {
    "joint": "j",
    "bone": "b",
    "joint_motion": "jm",
    "bone_motion": "bm",
}
EPOCH_SIZE = 55000
CONFIG_ROOT = Path("project/configs/stgcnpp/fps10_phase0")
JOB_ROOT = Path("project/slurm")
WORK_ROOT = Path("work_dirs/project/stgcnpp/fps10_phase0")
ANN_FILE = Path(
    "data/project/yolo26xpose/fps10_phase0/pyskl/continuous_window_w20_s4/"
    "radarv4_yolo26xpose_continuous_window_w20_s4_val_yunze.pkl"
)


def config_text(stream_name: str, summary: dict) -> str:
    stream = STREAMS[stream_name]
    counts = [summary["samples_per_split_class"]["train"][label] for label in LABELS]
    expected = sqrt_expected_draws(counts, EPOCH_SIZE)
    work_dir = f"./{WORK_ROOT.as_posix()}/{stream_name}"
    sampling_comment = "\n".join([
        "# Subject-wise project split:",
        f"# Train subjects: {', '.join(SPLIT_SUBJECTS['train'])}",
        "# Validation subject: yunze",
        f"# N_train = {sum(counts)}; requested samples per epoch = {EPOCH_SIZE}.",
        "# Square-root sampling with replacement: each sample has weight 1 / sqrt(n_yi).",
        "# With 4 GPUs, each rank receives 13,750 samples; no DDP padding is needed.",
        "# Natural train counts and expected requested draws per epoch:",
        *[
            f"# {index}: {label}: n={count}, expected={draw_count:.1f}"
            for index, (label, count, draw_count) in enumerate(zip(LABELS, counts, expected))
        ],
    ])
    pipelines = pipeline_block()
    if pipelines.count("clip_len=60") != 3:
        raise ValueError("Reference pipelines changed; review the project clip length before regenerating")
    pipelines = pipelines.replace("clip_len=60", "clip_len=20")
    return (
        "# Project ST-GCN++: 10 fps phase 0, 20-frame windows, stride 4.\n"
        f"# Stream: {stream_name} ({stream}). Generated by project/generate_stgcnpp_configs.py.\n"
        "# Reference: configs/stgcn++/stgcn++_radarv4/rerun/e1/fold_a/bone/b_continuous_window.py\n\n"
        f"stream = {stream!r}\n\n"
        "dataset_type = 'PoseDataset'\n"
        f"ann_file = {ANN_FILE.as_posix()!r}\n\n"
        + model_block() + "\n"
        + sampling_comment + "\n"
        + f"class_sample_strategy = 'sqrt'\nclass_sample_power = 0.5\nepoch_size = {EPOCH_SIZE}\n\n"
        + pipelines + "\n"
        + runtime_block(work_dir) + "\n"
        + """sampler_indices_output_dir = f'{work_dir}/sampler_indices'

# The test API exports best-checkpoint predictions on the validation subject.
# The project PKL contains only train/val; data.test therefore uses split='val'.
data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    persistent_workers=False,
    train_dataloader=dict(
        sampler_indices_output_dir=sampler_indices_output_dir,
        sampler_indices_output_prefix='sqrt_sampler'
    ),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split='train',
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='val'),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='val')
)
"""
    )


def job_text(stream_name: str) -> str:
    config_path = CONFIG_ROOT / f"{stream_name}.py"
    return f"""#!/bin/bash
#SBATCH --account=def-mbolic
#SBATCH --gpus-per-node=a100:4
#SBATCH --cpus-per-task=12
#SBATCH --mem=62G
#SBATCH --time=02:30:00
#SBATCH --job-name=project_10fps_{stream_name}
#SBATCH --output=project/slurm/%x_%j.out
#SBATCH --mail-user=yunzelu@outlook.com
#SBATCH --mail-type=BEGIN,END,FAIL

set -euo pipefail

module purge
module load StdEnv/2020 gcc/9.3.0 cuda/11.8 python/3.10 opencv/4.5.5
PROJECT_REPO_ROOT="${{PROJECT_REPO_ROOT:-${{HOME}}/projects/def-mbolic/yunzelu/pyskl}}"
source "${{PROJECT_REPO_ROOT}}/.venv/bin/activate"
cd "${{PROJECT_REPO_ROOT}}"

GPUS="${{GPUS:-4}}"
SEED="${{SEED:-42}}"
CONFIG="{config_path.as_posix()}"
ANN_FILE="{ANN_FILE.as_posix()}"

if [[ ! -f "${{CONFIG}}" || ! -f "${{ANN_FILE}}" ]]; then
  echo "[ERROR] Missing project config or dataset: ${{CONFIG}}, ${{ANN_FILE}}" >&2
  exit 1
fi

# --test-best writes best_pred.pkl and best_eval.json for yunze validation.
bash tools/dist_train.sh "${{CONFIG}}" "${{GPUS}}" \\
  --validate --test-best --seed "${{SEED}}" --deterministic
"""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # SLURM/Bash scripts must have LF line endings, including when generated on Windows.
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def main() -> None:
    if not ANN_FILE.is_file():
        raise FileNotFoundError(f"Build the project dataset first: {ANN_FILE}")
    summary_path = ANN_FILE.with_name(f"{ANN_FILE.stem}_summary.json")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if summary["subjects"] != SPLIT_SUBJECTS:
        raise ValueError("The project dataset must use yunze validation and the other 10 subjects for training")
    if summary["label_to_id"] != {label: index for index, label in enumerate(LABELS)}:
        raise ValueError("Project label map does not match the ST-GCN++ class order")
    protocol = summary["protocol_stats"]
    required = {"window_size": 20, "stride": 4, "nominal_fps": 10, "downsample_phase": 0}
    if any(protocol.get(key) != value for key, value in required.items()):
        raise ValueError("Expected the phase-0 10 fps dataset with 20-frame windows and stride 4")
    if sum(summary["samples_per_split_class"]["train"].values()) != summary["num_samples_by_split"]["train"]:
        raise ValueError("Training class counts do not match the split size")

    for stream_name in STREAMS:
        config_path = CONFIG_ROOT / f"{stream_name}.py"
        job_path = JOB_ROOT / f"train_{stream_name}.sh"
        write_text(config_path, config_text(stream_name, summary))
        write_text(job_path, job_text(stream_name))
        print(f"[DONE] {config_path} and {job_path}")


if __name__ == "__main__":
    main()
