# Project ST-GCN++: 10 fps phase 0, 20-frame windows, stride 4.
# Stream: joint_motion (jm). Generated by project/generate_stgcnpp_configs.py.
# Reference: configs/stgcn++/stgcn++_radarv4/rerun/e1/fold_a/bone/b_continuous_window.py

stream = 'jm'

dataset_type = 'PoseDataset'
ann_file = 'data/project/yolo26xpose/fps10_phase0/pyskl/continuous_window_w20_s4/radarv4_yolo26xpose_continuous_window_w20_s4_val_yunze.pkl'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        num_person=1,
        gcn_adaptive='init',
        gcn_with_res=True,
        tcn_type='mstcn',
        graph_cfg=dict(layout='coco', mode='spatial')
    ),
    cls_head=dict(
        type='GCNHead',
        num_classes=9,
        in_channels=256,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    )
)

# Subject-wise project split:
# Train subjects: chenzhe, dengdeng, han, hui, jiadi, li, mia, rose, saad, xilai
# Validation subject: yunze
# N_train = 54492; requested samples per epoch = 55000.
# Square-root sampling with replacement: each sample has weight 1 / sqrt(n_yi).
# With 4 GPUs, each rank receives 13,750 samples; no DDP padding is needed.
# Natural train counts and expected requested draws per epoch:
# 0: lie-stationary: n=10481, expected=9012.2
# 1: sit-stationary: n=5568, expected=6568.7
# 2: walk: n=23432, expected=13475.1
# 3: fall: n=1777, expected=3710.8
# 4: transition-lie-to-sit: n=2223, expected=4150.5
# 5: transition-lie-to-stand: n=4847, expected=6128.6
# 6: transition-sit-to-lie: n=1920, expected=3857.3
# 7: transition-sit-to-stand: n=1879, expected=3815.9
# 8: transition-stand-to-sit: n=2365, expected=4281.0
class_sample_strategy = 'sqrt'
class_sample_power = 0.5
epoch_size = 55000

# COCO-17 left/right keypoint ids
coco_left = [1, 3, 5, 7, 9, 11, 13, 15]
coco_right = [2, 4, 6, 8, 10, 12, 14, 16]

train_pipeline = [
    dict(
        type='Flip',
        flip_ratio=0.5,
        direction='horizontal',
        left_kp=coco_left,
        right_kp=coco_right
    ),
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=20),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

val_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=20),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

test_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=20),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

optimizer = dict(
    type='SGD',
    lr=0.05,
    momentum=0.9,
    weight_decay=0.0005,
    nesterov=True
)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False)
total_epochs = 20
checkpoint_config = dict(interval=1)
evaluation = dict(
    interval=1,
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,))),
    save_best='macro_f1',
    rule='greater'
)
test_evaluation = dict(
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,)))
)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
log_level = 'INFO'
load_from = None
resume_from = None
auto_resume = False
find_unused_parameters = False
work_dir = './work_dirs/project/stgcnpp/fps10_phase0/joint_motion'

sampler_indices_output_dir = f'{work_dir}/sampler_indices'

# The test API exports best-checkpoint predictions on the validation subject.
# The project PKL contains only train/val; data.test therefore uses split='val'.
data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    persistent_workers=False,
    train_dataloader=dict(
        sampler_indices_output_dir=sampler_indices_output_dir,
        sampler_indices_output_prefix='sqrt_sampler'
    ),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split='train',
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='val'),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='val')
)
