# ============================================================
# Rerun E1 validation-subject evaluation: C
# Base config: configs/stgcn++/stgcn++_radarv4/rerun/e1/fold_c/bone/c_triangular_temporal_composition.py
# Generated by rerun/e1/generate_validation_eval_scripts.py
# ============================================================

# ============================================================
# Rerun E1 C: continuous-window training with triangular temporal-composition targets
# Evaluation keeps the hard center-label continuous-window protocol.
# Fold C, stream bone
# Generated by rerun/e1/generate_stgcnpp_configs.py
# ============================================================

stream = 'b'
dataset_type = 'PoseDataset'
ann_file = 'data/radar_v4/rerun/yolo26xpose/pyskl/continuous_window_w60_s12_triangular/radarv4_yolo26xpose_continuous_window_w60_s12_triangular_fold_c.pkl'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN',
        in_channels=3,
        num_person=1,
        gcn_adaptive='init',
        gcn_with_res=True,
        tcn_type='mstcn',
        graph_cfg=dict(layout='coco', mode='spatial')
    ),
    cls_head=dict(
        type='GCNHead',
        num_classes=9,
        in_channels=256,
        dropout=0.5,
        loss_cls=dict(type='CrossEntropyLoss')
    )
)

# Subject-wise outer split:
# Train subjects: chenzhe, dengdeng, han, hui, jiadi, li, saad, xilai
# Validation subject: rose
# Calibration subject: mia
# Test subject: yunze
# Square-root training sampler:
# Each sample i has weight a_i = 1 / sqrt(n_yi).
# Sampling is with replacement; one epoch requests N_train samples.
# DDP may add <= world_size - 1 padded samples internally for equal rank lengths.
# N_train = 43335
# Natural train counts and expected requested draws per epoch:
# 0: lie-stationary: n=8015, expected=6948.1
# 1: sit-stationary: n=4473, expected=5190.6
# 2: walk: n=18686, expected=10608.9
# 3: fall: n=1414, expected=2918.4
# 4: transition-lie-to-sit: n=1766, expected=3261.4
# 5: transition-lie-to-stand: n=3920, expected=4859.1
# 6: transition-sit-to-lie: n=1581, expected=3085.9
# 7: transition-sit-to-stand: n=1528, expected=3033.7
# 8: transition-stand-to-sit: n=1952, expected=3428.9
# The sampler uses hard center labels from `label`; only the training
# pipeline replaces `label` with `label_soft_triangular` for the loss.
class_sample_strategy = 'sqrt'
class_sample_power = 0.5
epoch_size = 43335

# COCO-17 left/right keypoint ids
coco_left = [1, 3, 5, 7, 9, 11, 13, 15]
coco_right = [2, 4, 6, 8, 10, 12, 14, 16]

train_pipeline = [
    dict(
        type='Flip',
        flip_ratio=0.5,
        direction='horizontal',
        left_kp=coco_left,
        right_kp=coco_right
    ),
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='UseSoftLabel', source_key='label_soft_triangular', num_classes=9),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint', 'label'])
]

val_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

test_pipeline = [
    dict(type='PreNormalize2D', mode='auto'),
    dict(type='GenSkeFeat', dataset='coco', feats=[stream]),
    dict(type='MonotonicUniformResample', clip_len=60),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

optimizer = dict(
    type='SGD',
    lr=0.05,
    momentum=0.9,
    weight_decay=0.0005,
    nesterov=True
)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False)
total_epochs = 20
checkpoint_config = dict(interval=1)
evaluation = dict(
    interval=1,
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,))),
    save_best='macro_f1',
    rule='greater'
)
test_evaluation = dict(
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,)))
)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
log_level = 'INFO'
load_from = None
resume_from = None
auto_resume = False
find_unused_parameters = False
work_dir = './work_dirs/rerun/e1/fold_c/bone/c_triangular_temporal_composition'

sampler_indices_output_dir = f'{work_dir}/sampler_indices'

data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    persistent_workers=False,
    train_dataloader=dict(
        sampler_indices_output_dir=sampler_indices_output_dir,
        sampler_indices_output_prefix='sqrt_sampler'
    ),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=train_pipeline,
        split='train',
        class_sample_strategy=class_sample_strategy,
        class_sample_power=class_sample_power,
        epoch_size=epoch_size
    ),
    val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='val'),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='test')
)


# Validation-subject inference override.
work_dir = 'work_dirs/rerun/e1/fold_c/bone/c_triangular_temporal_composition/validation'
data['test'] = dict(data['val'])
test_evaluation = dict(
    metrics=['top_k_accuracy', 'macro_f1'],
    metric_options=dict(top_k_accuracy=dict(topk=(1,)))
)
