"""
Build a PYSKL PoseDataset annotation pkl from radar_v4 HPE JSONL files.

The skeleton arrays are read from JSONL files generated by hpe_jsonl.py. By
default, activity segments are read from data/radar_v4/origin so malformed AVI
metadata in old JSONLs cannot silently erase labels.

Example:
    python tools/data/radar_v4/build_pyskl_pkl.py ^
        --jsonl-root data/radar_v4/raw_jsonl/yolo26xpose ^
        --output data/radar_v4/pyskl/radar_v4_yolo26xpose_clip60.pkl ^
        --clip-len 60 ^
        --val-subject saad
"""

from __future__ import annotations

import argparse
import json
import pickle
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from stats_common import read_frame_label_rows, rows_to_segments


FINAL_LABELS = [
    "Falling",
    "Lying-Stationary",
    "Sit-Stationary",
    "Transition-LayBed-to-Sit",
    "Transition-LayFloor-to-Stand",
    "Transition-Sit-to-LayBed",
    "Transition-Sit-to-Stand",
    "Transition-Stand-to-Sit",
    "Walking",
]
LABEL_TO_ID = {label: idx for idx, label in enumerate(FINAL_LABELS)}

DROP_LABELS = {
    "Kneeling-Stationary",
    "Transition-Kneeling-to-Stand",
}

RENAME_LABELS = {
    "Transition-Sit-to-Laybed": "Transition-Sit-to-LayBed",
    "LayBed-Stationary": "Lying-Stationary",
    "LayFloor-Stationary": "Lying-Stationary",
}


@dataclass
class SessionData:
    jsonl_path: Path
    session_name: str
    subject: str
    source_video: str | None
    img_shape: tuple[int, int]
    keypoint: np.ndarray
    keypoint_score: np.ndarray | None
    segments: list[dict[str, Any]]
    label_source: str

    @property
    def total_frames(self) -> int:
        return int(self.keypoint.shape[0])


@dataclass
class BuildStats:
    jsonl_files: int = 0
    source_segments: int = 0
    samples_created: int = 0
    walking_windows_created: int = 0
    transition_segments_expanded: int = 0
    transition_segments_kept_original: int = 0
    stationary_segments_kept: int = 0
    dropped_segments_by_reason: Counter = field(default_factory=Counter)
    dropped_segments_by_label: Counter = field(default_factory=Counter)
    label_source_counts: Counter = field(default_factory=Counter)


def sanitize_id(text: str) -> str:
    text = text.strip()
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text)
    return text.strip("_") or "unknown"


def parse_subject_from_name(session_name: str) -> str:
    parts = session_name.split("-")
    if len(parts) >= 2:
        return parts[1]
    return "unknown"


def clean_label(label: Any) -> str | None:
    if label is None:
        return None

    label_text = str(label).strip()
    if not label_text or label_text.upper() in {"DELETE", "END"}:
        return None

    if label_text in DROP_LABELS:
        return None

    label_text = RENAME_LABELS.get(label_text, label_text)
    if label_text not in LABEL_TO_ID:
        return None

    return label_text


def is_transition_label(cleaned_label: str) -> bool:
    # Falling is a short dynamic segment in this dataset, so it follows the
    # same context-window policy as explicit Transition-* labels.
    return cleaned_label == "Falling" or cleaned_label.startswith("Transition-")


def is_stationary_label(cleaned_label: str) -> bool:
    return cleaned_label in {"Lying-Stationary", "Sit-Stationary"}


def is_walk_source(session: SessionData) -> bool:
    source_names = [
        session.session_name,
        session.jsonl_path.parent.name,
    ]
    if session.source_video:
        source_names.append(Path(session.source_video).stem)
        source_names.append(Path(session.source_video).parent.name)

    return any(name.lower().endswith("-walk") for name in source_names if name)


def read_jsonl(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    metadata: dict[str, Any] = {}
    frames: list[dict[str, Any]] = []

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            record = json.loads(line)
            record_type = record.get("type")
            if record_type == "metadata":
                metadata = record
            elif record_type == "frame":
                frames.append(record)

    frames.sort(key=lambda record: int(record.get("frame_idx", 0)))
    return metadata, frames


def infer_num_keypoints(frames: list[dict[str, Any]], default: int = 17) -> int:
    for frame in frames:
        keypoints = frame.get("keypoints_xy")
        if isinstance(keypoints, list) and keypoints:
            return len(keypoints)
    return default


def frames_to_arrays(
    frames: list[dict[str, Any]],
    num_keypoints: int,
) -> tuple[np.ndarray, np.ndarray | None]:
    if not frames:
        return (
            np.zeros((0, num_keypoints, 2), dtype=np.float32),
            np.zeros((0, num_keypoints), dtype=np.float32),
        )

    total_frames = max(int(frame.get("frame_idx", 0)) for frame in frames) + 1
    keypoint = np.zeros((total_frames, num_keypoints, 2), dtype=np.float32)
    keypoint_score = np.zeros((total_frames, num_keypoints), dtype=np.float32)
    has_score = False

    for frame in frames:
        frame_idx = int(frame.get("frame_idx", 0))
        keypoints_xy = frame.get("keypoints_xy")
        keypoints_conf = frame.get("keypoints_conf")

        if isinstance(keypoints_xy, list):
            for joint_idx, xy in enumerate(keypoints_xy[:num_keypoints]):
                if not isinstance(xy, list) or len(xy) < 2:
                    continue
                keypoint[frame_idx, joint_idx, 0] = float(xy[0])
                keypoint[frame_idx, joint_idx, 1] = float(xy[1])

        if isinstance(keypoints_conf, list):
            has_score = True
            for joint_idx, conf in enumerate(keypoints_conf[:num_keypoints]):
                if conf is None:
                    continue
                keypoint_score[frame_idx, joint_idx] = float(conf)

    return keypoint, keypoint_score if has_score else None


def metadata_segments(metadata: dict[str, Any]) -> list[dict[str, Any]]:
    segments = metadata.get("annotation_info", {}).get("segments", [])
    if not isinstance(segments, list):
        return []

    return [dict(seg) for seg in segments if isinstance(seg, dict)]


def frame_label_segments(frames: list[dict[str, Any]]) -> list[dict[str, Any]]:
    segments: list[dict[str, Any]] = []
    current_label = None
    current_group = "unlabeled"
    start_frame = None
    last_frame = None

    def close_segment(end_frame: int) -> None:
        if current_label is None or start_frame is None:
            return
        segments.append(
            {
                "start_frame": start_frame,
                "end_frame": end_frame,
                "label": current_label,
                "label_group": current_group,
                "length_frames": end_frame - start_frame + 1,
            }
        )

    for frame in frames:
        frame_idx = int(frame.get("frame_idx", 0))
        label = frame.get("label")
        label = label.strip() if isinstance(label, str) else None
        group = frame.get("label_group") or "unlabeled"

        if label != current_label:
            if last_frame is not None:
                close_segment(last_frame)
            current_label = label
            current_group = group
            start_frame = frame_idx if label is not None else None

        last_frame = frame_idx

    if last_frame is not None:
        close_segment(last_frame)

    return segments


def origin_segments(origin_root: Path, session_name: str) -> list[dict[str, Any]]:
    label_path = origin_root / session_name / "frame_labels.csv"
    if not label_path.exists():
        return []
    return rows_to_segments(read_frame_label_rows(label_path))


def choose_segments(
    metadata: dict[str, Any],
    frames: list[dict[str, Any]],
    session_name: str,
    origin_root: Path,
    label_source: str,
) -> tuple[list[dict[str, Any]], str]:
    origin = origin_segments(origin_root, session_name)
    jsonl_meta = metadata_segments(metadata)
    jsonl_frames = frame_label_segments(frames)

    if label_source == "origin":
        if origin:
            return origin, "origin"
        if jsonl_meta:
            return jsonl_meta, "jsonl_metadata_fallback"
        return jsonl_frames, "jsonl_frame_fallback"

    if label_source == "jsonl":
        if jsonl_meta:
            return jsonl_meta, "jsonl_metadata"
        return jsonl_frames, "jsonl_frame"

    if origin:
        return origin, "origin"
    if jsonl_meta:
        return jsonl_meta, "jsonl_metadata_fallback"
    return jsonl_frames, "jsonl_frame_fallback"


def clip_segments_to_session(
    segments: list[dict[str, Any]],
    total_frames: int,
) -> list[dict[str, Any]]:
    clipped: list[dict[str, Any]] = []

    for seg_idx, segment in enumerate(segments):
        start = int(segment["start_frame"])
        end = segment.get("end_frame")
        end = total_frames - 1 if end is None else int(end)

        start = max(start, 0)
        end = min(end, total_frames - 1)
        if total_frames <= 0 or start > end:
            continue

        item = dict(segment)
        item["source_segment_id"] = seg_idx
        item["start_frame"] = start
        item["end_frame"] = end
        item["length_frames"] = end - start + 1
        clipped.append(item)

    return clipped


def load_session(
    jsonl_path: Path,
    origin_root: Path,
    label_source: str,
) -> SessionData:
    metadata, frames = read_jsonl(jsonl_path)

    dataset_info = metadata.get("dataset_info", {})
    video_info = metadata.get("video_info", {})

    session_name = (
        dataset_info.get("session_name")
        or jsonl_path.parent.name
    )
    subject = dataset_info.get("subject") or parse_subject_from_name(session_name)
    source_video = video_info.get("video_path")

    height = int(video_info.get("height") or 480)
    width = int(video_info.get("width") or 640)

    num_keypoints = infer_num_keypoints(frames)
    keypoint, keypoint_score = frames_to_arrays(frames, num_keypoints)
    segments, used_label_source = choose_segments(
        metadata=metadata,
        frames=frames,
        session_name=session_name,
        origin_root=origin_root,
        label_source=label_source,
    )
    segments = clip_segments_to_session(segments, keypoint.shape[0])

    return SessionData(
        jsonl_path=jsonl_path,
        session_name=session_name,
        subject=subject,
        source_video=source_video,
        img_shape=(height, width),
        keypoint=keypoint,
        keypoint_score=keypoint_score,
        segments=segments,
        label_source=used_label_source,
    )


def centered_transition_window(
    start: int,
    end: int,
    clip_len: int,
    total_frames: int,
) -> tuple[int, int] | None:
    window_start = (start + end - clip_len + 1) // 2
    window_end = window_start + clip_len - 1

    if window_start < 0 or window_end >= total_frames:
        return None

    return window_start, window_end


def make_frame_dir(
    session_name: str,
    cleaned_label: str,
    sample_start: int,
    sample_end: int,
    source_segment_id: int,
    sample_type: str,
    sample_index: int,
) -> str:
    return (
        f"{sanitize_id(session_name)}__{sanitize_id(cleaned_label)}"
        f"__{sample_type}{sample_index:05d}"
        f"__seg{source_segment_id:04d}"
        f"__s{sample_start:06d}_e{sample_end:06d}"
    )


def build_annotation(
    session: SessionData,
    segment: dict[str, Any],
    cleaned_label: str,
    sample_start: int,
    sample_end: int,
    sample_type: str,
    sample_index: int,
) -> dict[str, Any]:
    source_segment_id = int(segment.get("source_segment_id", sample_index))
    frame_dir = make_frame_dir(
        session_name=session.session_name,
        cleaned_label=cleaned_label,
        sample_start=sample_start,
        sample_end=sample_end,
        source_segment_id=source_segment_id,
        sample_type=sample_type,
        sample_index=sample_index,
    )

    keypoint = session.keypoint[sample_start:sample_end + 1][None, ...].copy()

    annotation = {
        "frame_dir": frame_dir,
        "label": LABEL_TO_ID[cleaned_label],
        "label_name": cleaned_label,
        "original_label": segment.get("label"),
        "cleaned_label": cleaned_label,
        "subject": session.subject,
        "session_name": session.session_name,
        "source_video": session.source_video,
        "jsonl_path": str(session.jsonl_path),
        "label_source": session.label_source,
        "sample_type": sample_type,
        "segment_id": source_segment_id,
        "segment_start_frame": int(segment["start_frame"]),
        "segment_end_frame": int(segment["end_frame"]),
        "start_frame": sample_start,
        "end_frame": sample_end,
        "total_frames": int(sample_end - sample_start + 1),
        "img_shape": session.img_shape,
        "original_shape": session.img_shape,
        "keypoint": np.ascontiguousarray(keypoint),
    }

    if session.keypoint_score is not None:
        keypoint_score = session.keypoint_score[sample_start:sample_end + 1][None, ...].copy()
        annotation["keypoint_score"] = np.ascontiguousarray(keypoint_score)

    return annotation


def create_walking_windows(
    session: SessionData,
    segment: dict[str, Any],
    clip_len: int,
    next_sample_index: int,
) -> list[dict[str, Any]]:
    annotations: list[dict[str, Any]] = []
    start = int(segment["start_frame"])
    end = int(segment["end_frame"])

    window_start = start
    while window_start + clip_len - 1 <= end:
        window_end = window_start + clip_len - 1
        annotations.append(
            build_annotation(
                session=session,
                segment=segment,
                cleaned_label="Walking",
                sample_start=window_start,
                sample_end=window_end,
                sample_type="walk",
                sample_index=next_sample_index + len(annotations),
            )
        )
        window_start += clip_len

    return annotations


def create_transition_sample(
    session: SessionData,
    segment: dict[str, Any],
    cleaned_label: str,
    clip_len: int,
    sample_index: int,
) -> tuple[dict[str, Any] | None, bool]:
    start = int(segment["start_frame"])
    end = int(segment["end_frame"])
    length = end - start + 1

    if length >= clip_len:
        return (
            build_annotation(
                session=session,
                segment=segment,
                cleaned_label=cleaned_label,
                sample_start=start,
                sample_end=end,
                sample_type="transition",
                sample_index=sample_index,
            ),
            False,
        )

    window = centered_transition_window(
        start=start,
        end=end,
        clip_len=clip_len,
        total_frames=session.total_frames,
    )
    if window is None:
        return None, True

    window_start, window_end = window
    return (
        build_annotation(
            session=session,
            segment=segment,
            cleaned_label=cleaned_label,
            sample_start=window_start,
            sample_end=window_end,
            sample_type="transition_ctx",
            sample_index=sample_index,
        ),
        True,
    )


def create_stationary_sample(
    session: SessionData,
    segment: dict[str, Any],
    cleaned_label: str,
    sample_index: int,
) -> dict[str, Any]:
    return build_annotation(
        session=session,
        segment=segment,
        cleaned_label=cleaned_label,
        sample_start=int(segment["start_frame"]),
        sample_end=int(segment["end_frame"]),
        sample_type="stationary",
        sample_index=sample_index,
    )


def build_annotations(
    jsonl_root: Path,
    origin_root: Path,
    clip_len: int,
    label_source: str,
) -> tuple[list[dict[str, Any]], BuildStats]:
    annotations: list[dict[str, Any]] = []
    stats = BuildStats()
    jsonl_paths = sorted(jsonl_root.rglob("*.jsonl"))

    for jsonl_path in jsonl_paths:
        stats.jsonl_files += 1
        session = load_session(
            jsonl_path=jsonl_path,
            origin_root=origin_root,
            label_source=label_source,
        )
        stats.label_source_counts[session.label_source] += 1

        for segment in session.segments:
            stats.source_segments += 1
            original_label = segment.get("label")
            cleaned = clean_label(original_label)

            if cleaned is None:
                stats.dropped_segments_by_reason["label_cleaning"] += 1
                stats.dropped_segments_by_label[str(original_label)] += 1
                continue

            sample_index = len(annotations)

            if cleaned == "Walking":
                if not is_walk_source(session):
                    stats.dropped_segments_by_reason["walking_from_mixed_source"] += 1
                    stats.dropped_segments_by_label[str(original_label)] += 1
                    continue

                windows = create_walking_windows(
                    session=session,
                    segment=segment,
                    clip_len=clip_len,
                    next_sample_index=sample_index,
                )
                if not windows:
                    stats.dropped_segments_by_reason["walking_shorter_than_clip_len"] += 1
                    stats.dropped_segments_by_label[str(original_label)] += 1
                    continue

                annotations.extend(windows)
                stats.walking_windows_created += len(windows)
                continue

            if is_transition_label(cleaned):
                annotation, expanded = create_transition_sample(
                    session=session,
                    segment=segment,
                    cleaned_label=cleaned,
                    clip_len=clip_len,
                    sample_index=sample_index,
                )
                if annotation is None:
                    stats.dropped_segments_by_reason["transition_context_outside_source"] += 1
                    stats.dropped_segments_by_label[str(original_label)] += 1
                    print(
                        "[DROP] transition context outside source: "
                        f"{session.session_name} {original_label} "
                        f"{segment['start_frame']}-{segment['end_frame']}"
                    )
                    continue

                annotations.append(annotation)
                if expanded:
                    stats.transition_segments_expanded += 1
                else:
                    stats.transition_segments_kept_original += 1
                continue

            if is_stationary_label(cleaned):
                annotations.append(
                    create_stationary_sample(
                        session=session,
                        segment=segment,
                        cleaned_label=cleaned,
                        sample_index=sample_index,
                    )
                )
                stats.stationary_segments_kept += 1
                continue

            stats.dropped_segments_by_reason["unhandled_label"] += 1
            stats.dropped_segments_by_label[str(original_label)] += 1

    stats.samples_created = len(annotations)
    annotations.sort(key=lambda item: item["frame_dir"])
    return annotations, stats


def subjects_from_annotations(annotations: list[dict[str, Any]]) -> list[str]:
    return sorted({str(item["subject"]) for item in annotations})


def make_split(
    annotations: list[dict[str, Any]],
    val_subject: str | None,
) -> dict[str, list[str]]:
    split = {"train": [], "val": []}

    for item in annotations:
        target = "val" if val_subject is not None and item["subject"] == val_subject else "train"
        split[target].append(item["frame_dir"])

    return split


def count_by_class(annotations: list[dict[str, Any]], ids: list[str] | None = None) -> dict[str, int]:
    allowed = set(ids) if ids is not None else None
    counts = Counter()
    for item in annotations:
        if allowed is None or item["frame_dir"] in allowed:
            counts[item["label_name"]] += 1
    return {label: counts.get(label, 0) for label in FINAL_LABELS}


def count_by_subject(annotations: list[dict[str, Any]], ids: list[str] | None = None) -> dict[str, int]:
    allowed = set(ids) if ids is not None else None
    counts = Counter()
    for item in annotations:
        if allowed is None or item["frame_dir"] in allowed:
            counts[str(item["subject"])] += 1
    return dict(sorted(counts.items()))


def make_summary(
    annotations: list[dict[str, Any]],
    split: dict[str, list[str]],
    stats: BuildStats,
    output_pkl: Path,
    clip_len: int,
    val_subject: str | None,
) -> dict[str, Any]:
    by_split = {
        split_name: count_by_class(annotations, ids)
        for split_name, ids in split.items()
    }

    return {
        "output_pkl": str(output_pkl),
        "clip_len": clip_len,
        "val_subject": val_subject,
        "num_annotations": len(annotations),
        "num_train": len(split["train"]),
        "num_val": len(split["val"]),
        "label_to_id": LABEL_TO_ID,
        "samples_per_class": count_by_class(annotations),
        "samples_per_subject": count_by_subject(annotations),
        "samples_per_class_per_split": by_split,
        "samples_per_subject_per_split": {
            split_name: count_by_subject(annotations, ids)
            for split_name, ids in split.items()
        },
        "jsonl_files": stats.jsonl_files,
        "source_segments": stats.source_segments,
        "label_source_counts": dict(stats.label_source_counts),
        "dropped_segments_by_reason": dict(stats.dropped_segments_by_reason),
        "dropped_segments_by_label": dict(stats.dropped_segments_by_label),
        "dropped_by_label_cleaning": stats.dropped_segments_by_reason.get("label_cleaning", 0),
        "walking_windows_created": stats.walking_windows_created,
        "transition_segments_expanded_to_context": stats.transition_segments_expanded,
        "transition_segments_kept_original": stats.transition_segments_kept_original,
        "stationary_segments_kept": stats.stationary_segments_kept,
    }


def save_dataset(
    annotations: list[dict[str, Any]],
    split: dict[str, list[str]],
    stats: BuildStats,
    output_pkl: Path,
    clip_len: int,
    val_subject: str | None,
) -> None:
    output_pkl.parent.mkdir(parents=True, exist_ok=True)
    with output_pkl.open("wb") as f:
        pickle.dump(
            {
                "split": split,
                "annotations": annotations,
            },
            f,
            protocol=pickle.HIGHEST_PROTOCOL,
        )

    summary = make_summary(
        annotations=annotations,
        split=split,
        stats=stats,
        output_pkl=output_pkl,
        clip_len=clip_len,
        val_subject=val_subject,
    )
    summary_path = output_pkl.with_name(f"{output_pkl.stem}_summary.json")
    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    print(
        f"[DONE] {output_pkl} "
        f"(annotations={len(annotations)}, train={len(split['train'])}, val={len(split['val'])})"
    )
    print(f"[DONE] Summary: {summary_path}")


def loso_output_path(output: Path, subject: str) -> Path:
    return output.with_name(f"{output.stem}_loso_{sanitize_id(subject)}{output.suffix}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--jsonl-root",
        type=Path,
        default=Path("data/radar_v4/raw_jsonl/yolo26xpose"),
        help="Root folder containing extracted HPE JSONL files.",
    )
    parser.add_argument(
        "--origin-root",
        type=Path,
        default=Path("data/radar_v4/origin"),
        help="Root folder containing original frame_labels.csv annotations.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/radar_v4/pyskl/radar_v4_yolo26xpose_clip60.pkl"),
        help="Output pkl path. With --make-all-loso this is used as the base filename.",
    )
    parser.add_argument(
        "--clip-len",
        type=int,
        default=60,
        help="Fixed length for walking windows and short-transition context windows.",
    )
    parser.add_argument(
        "--val-subject",
        default=None,
        help="Held-out subject id/name for the validation split.",
    )
    parser.add_argument(
        "--make-all-loso",
        action="store_true",
        help="Generate one pkl per held-out subject.",
    )
    parser.add_argument(
        "--label-source",
        choices=["origin", "jsonl", "auto"],
        default="origin",
        help="Source for activity segments. Skeleton coordinates are always read from JSONL.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.clip_len <= 0:
        raise ValueError("--clip-len must be positive.")

    annotations, stats = build_annotations(
        jsonl_root=args.jsonl_root,
        origin_root=args.origin_root,
        clip_len=args.clip_len,
        label_source=args.label_source,
    )

    if not annotations:
        raise RuntimeError("No annotations were created.")

    subjects = subjects_from_annotations(annotations)
    print(f"[INFO] Subjects: {subjects}")
    print(f"[INFO] Label mapping: {LABEL_TO_ID}")

    if args.make_all_loso:
        for subject in subjects:
            split = make_split(annotations, val_subject=subject)
            save_dataset(
                annotations=annotations,
                split=split,
                stats=stats,
                output_pkl=loso_output_path(args.output, subject),
                clip_len=args.clip_len,
                val_subject=subject,
            )
        return

    if args.val_subject is not None and args.val_subject not in subjects:
        raise ValueError(
            f"--val-subject {args.val_subject!r} not found. "
            f"Available subjects: {subjects}"
        )

    split = make_split(annotations, val_subject=args.val_subject)
    save_dataset(
        annotations=annotations,
        split=split,
        stats=stats,
        output_pkl=args.output,
        clip_len=args.clip_len,
        val_subject=args.val_subject,
    )


if __name__ == "__main__":
    main()
