"""Run radar v4 PySKL inference directly on HPE JSONL files.

This accepts JSONL files generated by tools/data/radar_v4/hpe_jsonl.py. Each
frame record is converted into the same dense skeleton grid used by
infer_processed_pose_csv.py. Frames with no detection are filled with zero
keypoints and zero keypoint scores.

Sliding-window predictions are assigned to each window's center frame by
default, then expanded to a dense frame-level timeline by nearest center.

Example:
    python tools/data/radar_v4/infer_hpe_jsonl_timeline.py ^
        data/radar_v4/raw_jsonl/yolo26xpose/3-han-laysofa ^
        --output work_dirs/radar_v4_eval/3-han-laysofa_predictions.csv ^
        --stride 10 ^
        --overwrite
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

from infer_processed_pose_csv import (
    DEFAULT_CHECKPOINT,
    DEFAULT_CONFIG,
    DEFAULT_LABEL_MAP,
    NUM_KEYPOINTS,
    FrameGrid,
    build_timeline_scores,
    infer_window_predictions,
    load_label_map,
    resolve_device,
    write_predictions,
)


def iter_jsonl_paths(input_path: Path) -> list[Path]:
    if input_path.is_file():
        return [input_path]
    if input_path.is_dir():
        return sorted(path for path in input_path.glob("*.jsonl") if path.is_file())
    raise FileNotFoundError(input_path)


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def format_float(value: float) -> str:
    return f"{value:.9f}".rstrip("0").rstrip(".")


def load_jsonl_records(path: Path) -> tuple[dict[str, Any], dict[int, dict[str, Any]]]:
    metadata: dict[str, Any] = {}
    frames: dict[int, dict[str, Any]] = {}

    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue

            record = json.loads(line)
            record_type = record.get("type")
            if record_type == "metadata":
                metadata = record
            elif record_type == "frame":
                frame_idx = safe_int(record.get("frame_idx"), default=-1)
                if frame_idx >= 0:
                    frames[frame_idx] = record

    if not frames:
        raise ValueError(f"{path} contains no frame records")

    return metadata, frames


def metadata_img_shape(metadata: dict[str, Any]) -> tuple[int, int]:
    video_info = metadata.get("video_info", {}) if metadata else {}
    height = safe_int(video_info.get("height"), default=480)
    width = safe_int(video_info.get("width"), default=640)
    return height, width


def metadata_fps(metadata: dict[str, Any]) -> float:
    video_info = metadata.get("video_info", {}) if metadata else {}
    fps = safe_float(video_info.get("assumed_fps_used_for_timestamp"), default=0.0)
    if fps <= 0:
        fps = safe_float(video_info.get("reported_fps_from_cv2"), default=0.0)
    return fps if fps > 0 else 30.0


def metadata_total_frames(
    metadata: dict[str, Any],
    frames: dict[int, dict[str, Any]],
    trust_metadata_count: bool,
) -> int:
    max_frame = max(frames)
    if trust_metadata_count:
        video_info = metadata.get("video_info", {}) if metadata else {}
        count = safe_int(video_info.get("frame_count_from_cv2"), default=0)
        if count > max_frame:
            return count
    return max_frame + 1


def record_to_pose(record: dict[str, Any]) -> tuple["np.ndarray", "np.ndarray", bool]:
    import numpy as np

    keypoint = np.zeros((NUM_KEYPOINTS, 2), dtype=np.float32)
    keypoint_score = np.zeros(NUM_KEYPOINTS, dtype=np.float32)

    keypoints_xy = record.get("keypoints_xy")
    keypoints_conf = record.get("keypoints_conf")

    if not isinstance(keypoints_xy, list):
        return keypoint, keypoint_score, False

    for index, xy in enumerate(keypoints_xy[:NUM_KEYPOINTS]):
        if not isinstance(xy, list) or len(xy) < 2:
            continue
        keypoint[index, 0] = safe_float(xy[0])
        keypoint[index, 1] = safe_float(xy[1])

    if isinstance(keypoints_conf, list):
        for index, confidence in enumerate(keypoints_conf[:NUM_KEYPOINTS]):
            keypoint_score[index] = safe_float(confidence)
    else:
        for index in range(NUM_KEYPOINTS):
            if keypoint[index, 0] != 0 or keypoint[index, 1] != 0:
                keypoint_score[index] = 1.0

    detected = bool(record.get("detected")) and bool(keypoints_xy)
    return keypoint, keypoint_score, detected


def read_jsonl_frame_grid(
    jsonl_path: Path,
    kp_threshold: float,
    max_frames: int | None,
    trust_metadata_count: bool,
) -> tuple[FrameGrid, tuple[int, int]]:
    import numpy as np

    metadata, frames = load_jsonl_records(jsonl_path)
    img_shape = metadata_img_shape(metadata)
    fps = metadata_fps(metadata)
    total_frames = metadata_total_frames(
        metadata=metadata,
        frames=frames,
        trust_metadata_count=trust_metadata_count,
    )
    if max_frames is not None:
        total_frames = min(total_frames, max_frames)

    timestamps: list[str] = []
    timestamps_unix: list[float] = []
    keypoints: list[np.ndarray] = []
    keypoint_scores: list[np.ndarray] = []
    detection_counts: list[int] = []
    selected_detections: list[bool] = []

    zero_keypoint = np.zeros((NUM_KEYPOINTS, 2), dtype=np.float32)
    zero_score = np.zeros(NUM_KEYPOINTS, dtype=np.float32)

    for frame_idx in range(total_frames):
        record = frames.get(frame_idx)
        timestamp_sec = frame_idx / fps

        if record is None:
            keypoint = zero_keypoint.copy()
            keypoint_score = zero_score.copy()
            detection_count = 0
            selected_detection = False
        else:
            timestamp_sec = safe_float(record.get("timestamp_sec"), default=timestamp_sec)
            keypoint, keypoint_score, detected = record_to_pose(record)
            detection_count = safe_int(record.get("num_detections"), default=1 if detected else 0)
            selected_detection = detected and (
                safe_float(record.get("bbox_conf")) > 0
                or bool(np.any(keypoint_score > kp_threshold))
            )

        timestamps.append(format_float(timestamp_sec))
        timestamps_unix.append(math.nan)
        keypoints.append(keypoint)
        keypoint_scores.append(keypoint_score)
        detection_counts.append(detection_count)
        selected_detections.append(selected_detection)

    grid = FrameGrid(
        timestamps=timestamps,
        timestamps_unix=np.asarray(timestamps_unix, dtype=np.float64),
        keypoint=np.stack(keypoints).astype(np.float32, copy=False),
        keypoint_score=np.stack(keypoint_scores).astype(np.float32, copy=False),
        detection_count=np.asarray(detection_counts, dtype=np.int32),
        selected_detection=np.asarray(selected_detections, dtype=bool),
    )
    return grid, img_shape


def default_output_path(input_path: Path) -> Path:
    if input_path.is_file():
        return input_path.with_name(f"{input_path.stem}_timeline_predictions.csv")
    return input_path / "timeline_predictions.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run CTR-GCN radar v4 inference directly on an HPE JSONL session."
    )
    parser.add_argument(
        "input_path",
        type=Path,
        help="HPE JSONL file or a session folder containing one JSONL file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output frame-level prediction CSV.",
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--label-map", type=Path, default=DEFAULT_LABEL_MAP)
    parser.add_argument("--window-size", type=int, default=60)
    parser.add_argument("--stride", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument(
        "--timeline-mode",
        choices=["center", "window-average"],
        default="center",
        help="Default center assigns each window to its center and fills by nearest center.",
    )
    parser.add_argument(
        "--device",
        default="auto",
        help="Torch device, for example cuda:0 or cpu. Default: auto.",
    )
    parser.add_argument(
        "--kp-threshold",
        type=float,
        default=0.0,
        help="Keypoint confidence threshold for selected-detection accounting. Default: 0.",
    )
    parser.add_argument(
        "--min-valid-ratio",
        type=float,
        default=0.5,
        help="Minimum detected-frame ratio before a window is classified. Default: 0.5.",
    )
    parser.add_argument(
        "--min-valid-frames",
        type=int,
        help="Override --min-valid-ratio with an absolute frame count.",
    )
    parser.add_argument(
        "--no-tail-window",
        action="store_true",
        help="Do not add a final tail window when stride misses the final full window.",
    )
    parser.add_argument(
        "--ignore-metadata-frame-count",
        action="store_true",
        help="Use max JSONL frame_idx + 1 instead of metadata frame_count_from_cv2.",
    )
    parser.add_argument("--max-frames", type=int, help="Debug helper: read at most this many frames.")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    import numpy as np

    if args.window_size <= 0:
        raise ValueError("--window-size must be positive")
    if args.stride <= 0:
        raise ValueError("--stride must be positive")
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive")
    if args.min_valid_ratio < 0:
        raise ValueError("--min-valid-ratio must be non-negative")
    if args.min_valid_frames is not None and args.min_valid_frames < 0:
        raise ValueError("--min-valid-frames must be non-negative")

    jsonl_paths = iter_jsonl_paths(args.input_path)
    if len(jsonl_paths) != 1:
        raise ValueError(
            f"Expected exactly one JSONL file under {args.input_path}, found {len(jsonl_paths)}"
        )

    output_path = args.output or default_output_path(args.input_path)
    labels = load_label_map(args.label_map)
    device = resolve_device(args.device)

    grid, img_shape = read_jsonl_frame_grid(
        jsonl_path=jsonl_paths[0],
        kp_threshold=args.kp_threshold,
        max_frames=args.max_frames,
        trust_metadata_count=not args.ignore_metadata_frame_count,
    )

    if not args.quiet:
        print(f"[INFO] JSONL: {jsonl_paths[0]}")
        print(
            f"[INFO] Frames={grid.total_frames}, "
            f"selected_detection_frames={int(np.count_nonzero(grid.selected_detection))}, "
            f"img_shape={img_shape}, device={device}"
        )

    window_predictions, covering_windows, total_windows = infer_window_predictions(
        grid=grid,
        config_path=args.config,
        checkpoint_path=args.checkpoint,
        window_size=args.window_size,
        stride=args.stride,
        labels=labels,
        batch_size=args.batch_size,
        device=device,
        img_shape=img_shape,
        min_valid_ratio=args.min_valid_ratio,
        min_valid_frames=args.min_valid_frames,
        include_tail=not args.no_tail_window,
        quiet=args.quiet,
    )
    timeline = build_timeline_scores(
        total_frames=grid.total_frames,
        num_classes=len(labels),
        window_predictions=window_predictions,
        timeline_mode=args.timeline_mode,
    )

    write_predictions(
        output_path=output_path,
        grid=grid,
        labels=labels,
        timeline=timeline,
        covering_windows=covering_windows,
        overwrite=args.overwrite,
    )

    if not args.quiet:
        predicted_frames = int(np.count_nonzero(timeline.contributing_windows))
        print(f"[DONE] Wrote {grid.total_frames} frame predictions to {output_path}")
        print(f"[DONE] Valid windows: {len(window_predictions)}/{total_windows}")
        print(f"[DONE] Frames with model predictions: {predicted_frames}")


if __name__ == "__main__":
    main()
